language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py install
# command to run tests
script: nosetests
after_success: coveralls
# from url: http://docs.travis-ci.com/user/languages/python/
